sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: J8T6lrOxPfnkietZpkaH4JegQ/K1zjmCL1z7WeXdWwY+vxpMVSKqdmTn0p8U/VNTGv7XIt38aa7glhfdl4s574mtfDCCiPv/gSKuW+Ymcd/bejTqrVf2NWfeuItO/95wCAlYIE7GZAj8i3ZhibYmy0kaULiPUieD83fLMj0z3Y42yy7piqY9LfwOY/dkTwrmRhsxZbf29Q4yVpBnVH3dKBCkaEWH4OtAjCz3k8uOPq86daFAMBu9NGnv4/etqwHctCH1FHIMlJabxPgbktYeAHbzK+jRasqll5qH0k16cOEEebXt1yk4n0ed+g4zKXngzjTAUonDzamF5Ut5kmX7Kq5eHtf7iBoYm8asIp8bBkzK72AUGjwtQxRTJ1q+K0kk/l/DMJWLBTeCpb+E6JH8Ln75nNF2oWjz+BFoCvgz7AEi3KUqN8F3M9af2erZoLEq6+KjEUiMGZAfsEtAyn0sPhEJYr1e83vQBSHHejESHNlzPK0HyEg7NjS30CSh+Wz4LViRAwM7zSpz0NxjFD07gKFUEHW41qEUkbgQzDb6qcTeKqsr3rQKDkFQlbyWxz7gPJk3olsAz3qUpwVy96XlVbIjb6qrjm9loft9c2HIb9MZveN1dO0g+Fb8neY4bUFIxBARHW94lWabteRhJfkGNU+Mruo2ZpxSlPbELJH1Gxo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Froudacity--West-Indian-Fables-by-James-Anthony-Froude-Explained-by-J.-J.-Thomas_4068
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy